version = 0.1
[default.deploy.parameters]
stack_name = "ws-serverless-patterns-users"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-users"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "UserPoolAdminGroupName=\"apiAdmins\""
